### ISSUE TITLE
Upgrade to NXP BSP release L6.1.22-2.0.0

### ISSUE THREAD

**Issue by otavio** [Freescale/meta-freescale#1588]
The immediate items to work on are:

- [x] Upgrade Linux kernel and U-Boot (i.MX variants) - @MrCry0 
- [x] Upgrade Linux kernel and U-Boot (FSLC forks i.MX variants) #1608 
- [x] Upgrade OP-TEE @MrCry0  #1628 #1628
- [x]  ATF (i.MX variants) #1624
- [x] Upgrade Multimedia Packages #1627 #1627
- [x] Upgrade Graphics Packages #1611 #1635 
- [x] Jailhouse #1625
- [x] mcore-demos #1622

The Release Notes are [here](https://www.nxp.com/docs/en/release-note/IMX_LINUX_RELEASE_NOTES.pdf) for checking.

**Comment by dv1** [comment]
I'm looking at libimxdmabuffer, libimxvpuapi, and gstreamer-imx upgrades, along with improvements to the way `PACKAGECONFIG_GL` is set in gstreamer1.0-plugins-base. And I think these changes will be possible to backport to kirkstone and dunfell.

**Comment by MrCry0** [comment]
@otavio would you mind if I take the first task? Upgrade Linux kernel and U-Boot (i.MX variants)

**Comment by otavio** [comment]
@MrCry0, I added you to the description.

**Comment by dv1** [comment]
libimxdmabuffer, libimxvpuapi2, gstreamer-imx upgraded. PRs:

https://github.com/Freescale/meta-freescale/pull/1630
https://github.com/Freescale/meta-freescale/pull/1631
