### ISSUE TITLE
Upgrade BSP to LF6.1.55_2.2.0

### ISSUE THREAD

**Issue by angolini** [Freescale/meta-freescale#1715]
The immediate items to work on are:

- [x] Upgrade Linux kernel and headers (i.MX variants) @angolini #1727 
- [x] U-Boot (i.MX variants) #1718
- [x] Upgrade Linux kernel (FSLC forks i.MX variants)
- [x] Upgrade U-Boot (FSLC forks i.MX variants) #1757 
- [x] Upgrade OP-TEE #1752 
- [x] ATF (i.MX variants)  #1722 
- [x] Upgrade Multimedia Packages #1750 
- [x] Upgrade Graphics Packages #1723 
- [x] Jailhouse @angolini - #1748 
- [x] mcore-demos - #1740
- [x] firmware-imx*  - #1742
- [x] imx-mkimage #1719 
- [x] #1734 

The Release Notes are [here](https://www.nxp.com/docs/en/release-note/IMX_LINUX_RELEASE_NOTES.pdf) for checking.

**Comment by angolini** [comment]
Kernel subtasks:

- linux-fslc-imx_6.1.bb
  - [ ] From KBRANCH = "6.1-2.1.x-imx" to KBRANCH = "6.1-2.2.x-imx
  - [ ] kernel headers


- linux-fslc_6.1.bb
  - [ ] Keep the branch KBRANCH = "6.1.x+fslc" update the kernel stable version from v6.1.57 to v6.1.70
  - [ ] kernel headers


- linux-imx_6.1.bb
   - [ ] Keep the branch SRCBRANCH = "lf-6.1.y". But change the LOCALVERSION from -6.1.36-2.1.0 to -6.1.55-2.2.0 - https://github.com/Freescale/meta-freescale/pull/1727
   - [ ] kernel headers - https://github.com/Freescale/meta-freescale/pull/1728

**Comment by MrCry0** [comment]
@otavio I prepared the u-boot-fslc 2024.01 but don't have permissions to push it directly to `github.com/Freescale/u-boot-fslc.git`.

Please push the branch `https://github.com/MrCry0/u-boot-fslc/tree/2024.01%2Bfslc` into `Freescale/u-boot-fslc` so that I'll be able to update the u-boot fslc for this issue.

**Comment by otavio** [comment]
> @otavio I prepared the u-boot-fslc 2024.01 but don't have permissions to push it directly to `github.com/Freescale/u-boot-fslc.git`.
> 
> Please push the branch `https://github.com/MrCry0/u-boot-fslc/tree/2024.01%2Bfslc` into `Freescale/u-boot-fslc` so that I'll be able to update the u-boot fslc for this issue.

Done 👍🏻 thanks!
